import React from 'react'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ropoko | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>
          Hello World!
        </h1>
      </main>
    </div>
  )
}
